ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
ALTER TABLE roles ALTER COLUMN id TYPE BIGINT;

ALTER TABLE user_roles ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE user_roles ALTER COLUMN role_id TYPE BIGINT;

ALTER SEQUENCE users_id_seq AS BIGINT;
ALTER SEQUENCE roles_id_seq AS BIGINT;